### ISSUE TITLE
How to resolve the issue "Ensure that the professional version of Kendo UI is installed."?

### ISSUE THREAD

**Issue by adriatic** [aurelia-widgets/aurelia-kendoui#15]
We discussed this issue several times and I do not understand how to resolve it in today's repo (after merging in **[this PR](https://github.com/aurelia-widgets/aurelia-kendoui/pull/14)**)

The free KendoUI is properly installed now:

![image](https://cloud.githubusercontent.com/assets/2712405/10412841/9bfdccc4-6f60-11e5-99c7-f7b84f265df9.png)

However, when I select the Grid tab (see below)

![image](https://cloud.githubusercontent.com/assets/2712405/10412878/4bcb643a-6f62-11e5-8436-00e177dc8937.png)

I get 
```
ERROR [aurelia-kendoui] kendo.ui.Grid is not defined. Ensure that the professional version of Kendo UI is installed.
```

I know that the free KendoUI version that is installed by default does not contain the KendoUI PRO components and was under the impression that in order to enable these components I would have to stuff the `kendo.all.min.js` file into newly added `vendor` folder:

![image](https://cloud.githubusercontent.com/assets/2712405/10412905/4ff51712-6f63-11e5-9845-b7c718c0fe39.png)

That is clearly not what is happening, so Jedd, please tell me what is the right way (stuff the whole KendoUI PRO to `vendor` folder??)

**Comment by davidpurkiss** [comment]
I noted some discussion around this a few days ago but I never saw what was decided if anything. So I'm not sure if this is the decided way of resolving this but here goes.

* Copy [KendoUIPro]\src\js\kendo.all.js to jspm_packages\github\kendo-labs\bower-kendo-ui@2015.2.813\src\js
* Navigate to jspm_packages\github\kendo-labs\bower-kendo-ui@2015.2.813.js
* Modify the single line in this file so that it looks like 'module.exports = require("github:kendo-labs/bower-kendo-ui@2015.2.813/src/js/kendo.all");'

I do hope official JSPM support will come soon.

**Comment by adriatic** [comment]
The answer is a lot simpler - found it a few minutes after creating this issue. I simply missed to un-comment the line `import kendo` shown below:

```javascript
import 'bootstrap';
// Uncomment this line to use Kendo UI professional. You must place kendo.all.js
// in the `vendor` directory.
// import 'kendo';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging();

  //Uncomment the line below to enable animation.
  aurelia.use.plugin('aurelia-animator-css');

  //Anyone wanting to use HTMLImports to load views, will need to install the following plugin.
  //aurelia.use.plugin('aurelia-html-import-template-loader')

  aurelia.start().then(a => a.setRoot());
}
```

**Comment by davidpurkiss** [comment]
Ah, I was wondering what that was for.
